### ISSUE TITLE
Error when go in admin

### ISSUE THREAD

**Issue by imongithubnow** [CaptainN/meteor-react-starter#10]
Hi,
I wan to try your example but just sart and go in /admin route, show error in browser console:
`Uncaught TypeError: useTracker is not a function`
in App.js:35

**Comment by CaptainN** [comment]
Looks like i need to do some updates! `useTracker` should be imported from `meteor/react-meteor-data` instead of `meteor/npdev:collections`. Update that, and you should be good to go.

**Comment by imongithubnow** [comment]
Thanx.
