### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by SachaG** [CaptainN/meteor-react-starter#2]
I tried contacting you via CaptainN@unFocus.com but didn't get any reply. Is there a better way to contact you? I would love to talk more about using this inside http://vulcanjs.org.

**Comment by CaptainN** [comment]
Oh hey - I don't check that email much (where did you find that?). You can use kevin@unfocus.com to contact me through email.

**Comment by CaptainN** [comment]
It was in my profile! I fixed it.
